export const categories = [
  { id: 'rice', name: 'Rice', emoji: '🍚', color: 'from-amber-300 to-yellow-500', count: 4 },
  { id: 'atta-flour', name: 'Atta & Flour', emoji: '🌾', color: 'from-stone-300 to-orange-400', count: 3 },
  { id: 'dal-pulses', name: 'Dal & Pulses', emoji: '🫘', color: 'from-orange-300 to-red-400', count: 4 },
  { id: 'oils-ghee', name: 'Oils & Ghee', emoji: '🫒', color: 'from-lime-300 to-emerald-500', count: 3 },
  { id: 'daily-use', name: 'Daily Use', emoji: '🧼', color: 'from-sky-300 to-cyan-500', count: 4 },
  { id: 'spices', name: 'Spices', emoji: '🌶️', color: 'from-rose-300 to-orange-500', count: 2 },
];

export const products = [
  {
    id: 1,
    name: 'Basmati Rice',
    category: 'rice',
    price: 12.99,
    originalPrice: 14.49,
    discount: 10,
    unit: '5kg',
    rating: 4.8,
    reviews: 420,
    inStock: true,
    badge: 'Bestseller',
    description: 'Premium long grain basmati rice for daily meals and special dishes.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    tags: ['rice', 'staples', 'daily'],
  },
  {
    id: 2,
    name: 'Sona Masoori Rice',
    category: 'rice',
    price: 10.49,
    originalPrice: 11.49,
    discount: 9,
    unit: '5kg',
    rating: 4.6,
    reviews: 312,
    inStock: true,
    badge: null,
    description: 'Light and aromatic rice, perfect for daily home cooking.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    tags: ['rice', 'everyday', 'staples'],
  },
  {
    id: 3,
    name: 'Whole Wheat Atta',
    category: 'atta-flour',
    price: 8.99,
    originalPrice: 9.99,
    discount: 10,
    unit: '5kg',
    rating: 4.7,
    reviews: 355,
    inStock: true,
    badge: 'Fresh Milled',
    description: 'Stone-ground whole wheat atta for soft rotis and chapatis.',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400&h=400&fit=crop',
    tags: ['atta', 'flour', 'daily'],
  },
  {
    id: 4,
    name: 'Besan Flour',
    category: 'atta-flour',
    price: 2.79,
    originalPrice: 3.19,
    discount: 13,
    unit: '1kg',
    rating: 4.5,
    reviews: 198,
    inStock: true,
    badge: null,
    description: 'Fine gram flour for pakoras, cheela, and home snacks.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=400&fit=crop',
    tags: ['besan', 'flour', 'kitchen'],
  },
  {
    id: 5,
    name: 'Toor Dal',
    category: 'dal-pulses',
    price: 4.49,
    originalPrice: 4.99,
    discount: 10,
    unit: '1kg',
    rating: 4.6,
    reviews: 246,
    inStock: true,
    badge: null,
    description: 'Unpolished toor dal for everyday dal and sambhar.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['dal', 'pulses', 'protein'],
  },
  {
    id: 6,
    name: 'Moong Dal',
    category: 'dal-pulses',
    price: 4.29,
    originalPrice: 4.79,
    discount: 10,
    unit: '1kg',
    rating: 4.7,
    reviews: 221,
    inStock: true,
    badge: 'High Protein',
    description: 'Clean and sorted moong dal for quick, healthy meals.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['dal', 'moong', 'protein'],
  },
  {
    id: 7,
    name: 'Chana Dal',
    category: 'dal-pulses',
    price: 3.99,
    originalPrice: 4.29,
    discount: 7,
    unit: '1kg',
    rating: 4.5,
    reviews: 186,
    inStock: true,
    badge: null,
    description: 'Nutty and rich chana dal for curries and snacks.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['dal', 'chana', 'pulses'],
  },
  {
    id: 8,
    name: 'Sunflower Oil',
    category: 'oils-ghee',
    price: 6.49,
    originalPrice: 6.99,
    discount: 7,
    unit: '1L',
    rating: 4.6,
    reviews: 275,
    inStock: true,
    badge: null,
    description: 'Refined sunflower oil suitable for everyday cooking.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
    tags: ['oil', 'cooking', 'daily'],
  },
  {
    id: 9,
    name: 'Mustard Oil',
    category: 'oils-ghee',
    price: 7.49,
    originalPrice: 7.99,
    discount: 6,
    unit: '1L',
    rating: 4.7,
    reviews: 164,
    inStock: true,
    badge: 'Cold Pressed',
    description: 'Strong and pure mustard oil for traditional flavor.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
    tags: ['oil', 'mustard', 'cooking'],
  },
  {
    id: 10,
    name: 'Cow Ghee',
    category: 'oils-ghee',
    price: 9.99,
    originalPrice: 11.49,
    discount: 13,
    unit: '500ml',
    rating: 4.8,
    reviews: 203,
    inStock: true,
    badge: 'Pure',
    description: 'Rich aromatic ghee for tadka, rotis, and sweets.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=400&fit=crop',
    tags: ['ghee', 'dairy-fat', 'kitchen'],
  },
  {
    id: 11,
    name: 'Bath Soap Pack',
    category: 'daily-use',
    price: 2.99,
    originalPrice: 3.49,
    discount: 14,
    unit: '4 pcs',
    rating: 4.4,
    reviews: 418,
    inStock: true,
    badge: null,
    description: 'Mild fragrance bath soap for everyday family use.',
    image: 'https://images.unsplash.com/photo-1607006483225-9d5cbfb9fc44?w=400&h=400&fit=crop',
    tags: ['soap', 'hygiene', 'daily-use'],
  },
  {
    id: 12,
    name: 'Dishwash Liquid',
    category: 'daily-use',
    price: 1.99,
    originalPrice: 2.29,
    discount: 13,
    unit: '500ml',
    rating: 4.5,
    reviews: 267,
    inStock: true,
    badge: 'Lemon Fresh',
    description: 'Grease-cutting dishwash liquid for daily kitchen cleaning.',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
    tags: ['cleaning', 'kitchen', 'daily-use'],
  },
  {
    id: 13,
    name: 'Laundry Detergent',
    category: 'daily-use',
    price: 4.29,
    originalPrice: 4.79,
    discount: 10,
    unit: '1kg',
    rating: 4.5,
    reviews: 194,
    inStock: true,
    badge: null,
    description: 'Front and top load compatible detergent powder.',
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&h=400&fit=crop',
    tags: ['detergent', 'laundry', 'daily-use'],
  },
  {
    id: 14,
    name: 'Iodized Salt',
    category: 'spices',
    price: 0.79,
    originalPrice: 0.99,
    discount: 20,
    unit: '1kg',
    rating: 4.7,
    reviews: 536,
    inStock: true,
    badge: 'Essential',
    description: 'Free-flow refined iodized salt for everyday cooking.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['salt', 'spices', 'kitchen'],
  },
  {
    id: 15,
    name: 'Turmeric Powder',
    category: 'spices',
    price: 1.49,
    originalPrice: 1.69,
    discount: 12,
    unit: '200g',
    rating: 4.6,
    reviews: 145,
    inStock: true,
    badge: null,
    description: 'Natural turmeric powder for color, taste, and wellness.',
    image: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=400&h=400&fit=crop',
    tags: ['spice', 'turmeric', 'cooking'],
  },
  {
    id: 16,
    name: 'Masoor Dal',
    category: 'dal-pulses',
    price: 3.89,
    originalPrice: 4.19,
    discount: 7,
    unit: '1kg',
    rating: 4.6,
    reviews: 171,
    inStock: true,
    badge: null,
    description: 'Quick-cook red lentils, perfect for daily dal.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['dal', 'masoor', 'staples'],
  },
  {
    id: 17,
    name: 'Parboiled Rice',
    category: 'rice',
    price: 9.79,
    originalPrice: 10.29,
    discount: 5,
    unit: '5kg',
    rating: 4.4,
    reviews: 108,
    inStock: true,
    badge: null,
    description: 'Nutritious parboiled rice for daily family meals.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    tags: ['rice', 'staples', 'daily'],
  },
  {
    id: 18,
    name: 'Maida Flour',
    category: 'atta-flour',
    price: 1.89,
    originalPrice: 2.19,
    discount: 13,
    unit: '1kg',
    rating: 4.3,
    reviews: 95,
    inStock: true,
    badge: null,
    description: 'Fine flour for baking, snacks, and festive recipes.',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400&h=400&fit=crop',
    tags: ['flour', 'maida', 'kitchen'],
  },
  {
    id: 19,
    name: 'Toothpaste Family Pack',
    category: 'daily-use',
    price: 3.49,
    originalPrice: 3.99,
    discount: 13,
    unit: '3 x 150g',
    rating: 4.6,
    reviews: 289,
    inStock: true,
    badge: 'Value Pack',
    description: 'Family-value toothpaste pack for daily oral care.',
    image: 'https://images.unsplash.com/photo-1559591937-abc0b364be9f?w=400&h=400&fit=crop',
    tags: ['toothpaste', 'oral-care', 'daily-use'],
  },
  {
    id: 20,
    name: 'Groundnut Oil',
    category: 'oils-ghee',
    price: 7.19,
    originalPrice: 7.79,
    discount: 8,
    unit: '1L',
    rating: 4.5,
    reviews: 134,
    inStock: true,
    badge: null,
    description: 'Balanced flavor groundnut oil for everyday cooking.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
    tags: ['oil', 'groundnut', 'kitchen'],
  },
  {
    id: 21,
    name: 'Urad Dal',
    category: 'dal-pulses',
    price: 4.59,
    originalPrice: 4.99,
    discount: 8,
    unit: '1kg',
    rating: 4.5,
    reviews: 112,
    inStock: false,
    badge: null,
    description: 'Quality urad dal for idli, dosa, and curries.',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e6?w=400&h=400&fit=crop',
    tags: ['dal', 'urad', 'staples'],
  },
  {
    id: 22,
    name: 'Poha (Flattened Rice)',
    category: 'rice',
    price: 1.79,
    originalPrice: 1.99,
    discount: 10,
    unit: '500g',
    rating: 4.4,
    reviews: 123,
    inStock: true,
    badge: null,
    description: 'Light flattened rice for quick breakfast and snacks.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    tags: ['poha', 'rice', 'breakfast'],
  },
  {
    id: 23,
    name: 'Red Chilli Powder',
    category: 'spices',
    price: 1.59,
    originalPrice: 1.89,
    discount: 16,
    unit: '200g',
    rating: 4.3,
    reviews: 86,
    inStock: true,
    badge: null,
    description: 'Bright and spicy chilli powder for daily cooking.',
    image: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=400&h=400&fit=crop',
    tags: ['spice', 'chilli', 'kitchen'],
  },
  {
    id: 24,
    name: 'Handwash Refill',
    category: 'daily-use',
    price: 2.19,
    originalPrice: 2.49,
    discount: 12,
    unit: '750ml',
    rating: 4.4,
    reviews: 152,
    inStock: true,
    badge: null,
    description: 'Gentle handwash refill pack for regular home use.',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
    tags: ['hygiene', 'handwash', 'daily-use'],
  },
  {
    id: 25,
    name: 'Jaggery Powder',
    category: 'spices',
    price: 2.49,
    originalPrice: 2.89,
    discount: 14,
    unit: '500g',
    rating: 4.5,
    reviews: 97,
    inStock: true,
    badge: 'Natural',
    description: 'Natural jaggery powder for tea, sweets, and cooking.',
    image: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=400&h=400&fit=crop',
    tags: ['jaggery', 'sweetener', 'kitchen'],
  },
  {
    id: 26,
    name: 'Rava (Semolina)',
    category: 'atta-flour',
    price: 1.99,
    originalPrice: 2.29,
    discount: 13,
    unit: '1kg',
    rating: 4.4,
    reviews: 104,
    inStock: true,
    badge: null,
    description: 'Fine rava for upma, halwa, and breakfast recipes.',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400&h=400&fit=crop',
    tags: ['rava', 'semolina', 'kitchen'],
  },
  {
    id: 27,
    name: 'Tissue Paper Pack',
    category: 'daily-use',
    price: 2.39,
    originalPrice: 2.69,
    discount: 11,
    unit: '6 rolls',
    rating: 4.5,
    reviews: 209,
    inStock: true,
    badge: null,
    description: 'Soft tissue roll pack for daily household use.',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
    tags: ['tissue', 'home-care', 'daily-use'],
  },
  {
    id: 28,
    name: 'Idli Rice',
    category: 'rice',
    price: 7.99,
    originalPrice: 8.49,
    discount: 6,
    unit: '5kg',
    rating: 4.6,
    reviews: 88,
    inStock: true,
    badge: null,
    description: 'Special idli rice for soft batter and fluffy idlis.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    tags: ['rice', 'idli', 'south-indian'],
  },
];

export const offerBanners = [
  {
    id: 1,
    title: 'Daily Rice Deals',
    subtitle: 'Save on basmati, sona masoori, and idli rice',
    cta: 'Shop Now',
    gradient: 'from-amber-500 to-yellow-700',
    emoji: '🍚',
    category: 'rice',
  },
  {
    id: 2,
    title: 'Atta + Dal Combo',
    subtitle: 'Kitchen essentials for everyday meals',
    cta: 'Order Now',
    gradient: 'from-orange-500 to-red-600',
    emoji: '🌾',
    category: 'dal-pulses',
  },
  {
    id: 3,
    title: 'Home Care Picks',
    subtitle: 'Soap, handwash, detergent and more daily use',
    cta: 'Grab Deals',
    gradient: 'from-sky-500 to-cyan-700',
    emoji: '🧼',
    category: 'daily-use',
  },
];

export const getFeaturedProducts = () => products.filter((p) => p.rating >= 4.6).slice(0, 8);
export const getProductsByCategory = (categoryId) => products.filter((p) => p.category === categoryId);
export const getProductById = (id) => products.find((p) => p.id === Number(id));
export const getRelatedProducts = (product) =>
  products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, 4);
